
@echo off

REM !!! Generated by the fmp-cli 1.83.0.  DO NOT EDIT!

md MultipleDesktops\Assets\3rd\fmp-xtc-multipledesktops

cd ..\vs2022
dotnet build -c Release

copy fmp-xtc-multipledesktops-lib-mvcs\bin\Release\netstandard2.1\*.dll ..\unity2021\MultipleDesktops\Assets\3rd\fmp-xtc-multipledesktops\
